version: "3.7"
services:
  db:
    image: postgres:15.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
    volumes:
      - odoo18-db1-data:/var/lib/postgresql/data 
    
  odoo_web:
    image: odoo:18
   
    ports:
      - "80118:8069"
    volumes:
      - ./odoo_addons:/odoo_addons
      - ./odoo-enterprise:/enterprise-18
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo18-web-data:/var/lib/odoo
    #command:
      #-d db_name 
      #--update all
      

volumes:
  odoo18-web-data:
  odoo18-db1-data:


